"""Canonical marker (Junkman token) display names from the game's FE data.

Index = ePossibleMarker (see core/junkman.py; MARKER_LAST = 21). Source:
MarkerSelectInfo table in speed.exe v1.3 (file offset 0x505ED0, 22 records
x 0x1C, stored in display order with the true enum id in a chain field),
label hashes resolved through LANGUAGES/Labels.bin and display strings
through LANGUAGES/English.bin (chunk 0x00039000 hash tables).

FE facts worth knowing:
- DECAL (15) and PAINT (16) are nameless in the FE table (null label
  hashes) — the marker-select screen never names them; they are absent
  here and callers must keep their own fallback names.
- INDUCTION (4) is displayed by the game as "Unique Supercharger
  Upgrades" (label MARKER_NAME_SUPERCHARGER); turbo and supercharger are
  one marker type, split by the marker's Param at grant time.
- The engine groups markers into FOUR FE categories (Performance / Parts /
  Visual / Bonus Markers); the editor keeps its historical 3-way grouping
  (Performance / Visual / Police) on purpose — fe_category here is the
  game's grouping, not the editor's.
- The CASH (19) description carries the engine's printf placeholder
  ("%$d") verbatim.

Generated by RE/tools/gen_token_names.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Dict, NamedTuple, Optional


class MarkerCanon(NamedTuple):
    label: str         # engine label name (MARKER_NAME_*)
    name: str          # marker-select screen title
    fe_category: str   # FE category title (game's 4-way grouping)
    description: str   # marker-select screen description


MARKER_CANON: Dict[int, MarkerCanon] = {
    1: MarkerCanon(
        "MARKER_NAME_BRAKES",
        "Unique Brake Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique brake upgrade on any of your cars.",
    ),
    2: MarkerCanon(
        "MARKER_NAME_ENGINE",
        "Unique Engine Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique engine upgrade on any of your cars.",
    ),
    3: MarkerCanon(
        "MARKER_NAME_NOS",
        "Unique Nitrous Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique nitrous upgrade on any of your cars.",
    ),
    4: MarkerCanon(
        "MARKER_NAME_SUPERCHARGER",
        "Unique Supercharger Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique supercharger upgrade on any car that accepts supercharger kits.",
    ),
    5: MarkerCanon(
        "MARKER_NAME_CHASSI",
        "Unique Suspension Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique suspension upgrade on any of your cars.",
    ),
    6: MarkerCanon(
        "MARKER_NAME_TIRE",
        "Unique Tire Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique tire upgrade on any of your cars.",
    ),
    7: MarkerCanon(
        "MARKER_NAME_TRANSMISSION",
        "Unique Transmission Upgrades",
        "Unique Performance Upgrades",
        "Backroom pass to the One Stop Shop for a unique transmission upgrade on any of your cars.",
    ),
    8: MarkerCanon(
        "MARKER_NAME_BODYKIT",
        "Unique Body Kit Upgrades",
        "Unique Part Upgrades",
        "Backroom pass to the One Stop Shop for a unique body kit upgrade on any of your cars.",
    ),
    9: MarkerCanon(
        "MARKER_NAME_HOOD",
        "Unique Hood Upgrades",
        "Unique Part Upgrades",
        "Backroom pass to the One Stop Shop for a unique hood upgrade on any of your cars.",
    ),
    10: MarkerCanon(
        "MARKER_NAME_SPOILER",
        "Unique Spoiler Upgrades",
        "Unique Part Upgrades",
        "Backroom pass to the One Stop Shop for a unique spoiler upgrade on any of your cars.",
    ),
    11: MarkerCanon(
        "MARKER_NAME_RIMS",
        "Unique Rim Upgrades",
        "Unique Part Upgrades",
        "Backroom pass to the One Stop Shop for a unique rim upgrade on any of your cars.",
    ),
    12: MarkerCanon(
        "MARKER_NAME_ROOFSCOOPS",
        "Unique Roof Scoop Upgrades",
        "Unique Part Upgrades",
        "Backroom pass to the One Stop Shop for a unique roof scoop upgrade on any of your cars.",
    ),
    13: MarkerCanon(
        "MARKER_NAME_HUD",
        "Unique Custom Gauge Upgrades",
        "Unique Visual Upgrades",
        "Backroom pass to the One Stop Shop for a unique custom gauge upgrade on any of your cars.",
    ),
    14: MarkerCanon(
        "MARKER_NAME_VINYLS",
        "Unique Vinyl Upgrades",
        "Unique Visual Upgrades",
        "Backroom pass to the One Stop Shop for a unique vinyl upgrade on any of your cars.",
    ),
    17: MarkerCanon(
        "MARKER_NAME_FREEBAIL",
        "Get out of jail for free.",
        "Bonus Markers",
        "Get out of jail for free next time you get busted.",
    ),
    18: MarkerCanon(
        "MARKER_NAME_PINKSLIP",
        "Pink slip to Blacklist rival",
        "Bonus Markers",
        "You just scored the pink slip for the rival racer's car. The next time you go to your safe house you'll see the car waiting for you.",
    ),
    19: MarkerCanon(
        "MARKER_NAME_CASH",
        "Extra Cash Reward",
        "Bonus Markers",
        "You just scored an extra %$d in cash.",
    ),
    20: MarkerCanon(
        "MARKER_NAME_IMPOUND",
        "Extra impound strike",
        "Bonus Markers",
        "You have the option of increasing the allowed impound strikes on any of your cars by 1. Maximum allowed is 5 on any single car.",
    ),
    21: MarkerCanon(
        "MARKER_NAME_RELEASE",
        "Release car from impound",
        "Bonus Markers",
        "Get any car you want out of impound.",
    ),
}


def canon_name(marker_id: int) -> Optional[str]:
    """In-game marker title, or None (DECAL/PAINT are nameless in FE)."""
    entry = MARKER_CANON.get(marker_id)
    return entry.name if entry else None


def canon_description(marker_id: int) -> Optional[str]:
    """In-game marker description, or None."""
    entry = MARKER_CANON.get(marker_id)
    return entry.description if entry else None


def canon_fe_category(marker_id: int) -> Optional[str]:
    """The game's own FE category title for a marker, or None."""
    entry = MARKER_CANON.get(marker_id)
    return entry.fe_category if entry else None


# The language files also ship an (unwired) turbo variant for INDUCTION (4);
# the editor prefers this wording since the marker grants turbo far more
# often than supercharger and the editor historically called the card Turbo.
INDUCTION_TURBO_NAME: str = "Unique Turbo Upgrades"
INDUCTION_TURBO_DESCRIPTION: str = "Backroom pass to the One Stop Shop for a unique turbo upgrade on any car that accepts turbo kits."
