"""GMilestone / speedtrap key names: lookup2 hash -> engine name.

TypeKeys are pursuit-stat identifiers (8 used by career milestones; the
MilestoneType[30] table tracks 30 in total, including cut-content ticket
stats). ChallengeKeys and speedtrap keys are VLT node paths of the form
milestones/bin_NN/challenge_NN_<stat> and speedtraps/bin_NN/speedtrapN.
Speedtrap required/best speeds in the save are stored in m/s.

Known EA data quirk: bounty milestones (type bounty_in_pursuit) live in VLT
nodes named challenge_N_cops_destroyed — the mechanic was renamed during
development, the node names were not.

Generated by RE/tools/gen_milestone_names.py from the game's VLT binaries
(every hash re-verified as lookup2 of its name). Do not edit by hand.
"""
from __future__ import annotations

from typing import Dict, Optional, Tuple

# All MilestoneType stat hashes (used + unused).
MILESTONE_TYPE_NAMES: Dict[int, str] = {
    0x033FA23A: "pursuit_length",
    0x1334DAE6: "margin_of_victory",
    0x15E88693: "hit_and_run_ticket",
    0x1BF724E1: "damage_property_ticket",
    0x20F1AEF3: "helis_in_pursuit",
    0x2377E50D: "bounty_in_pursuit",
    0x23B1BF0E: "insurance_claims",
    0x254230F5: "911_calls",
    0x2CB7CAF4: "pursuits_in_a_row",
    0x3FD1884D: "cops_destroyed_in_pursuit",
    0x411B084E: "outrun_pursuits_won",
    0x4D9777F1: "fleeing_ticket",
    0x4FC942CA: "cops_destroyed",
    0x5392E4FD: "pursuit_evasion_time",
    0x7457EED4: "outrun_races_won",
    0x755F7845: "driving_sidewalk_ticket",
    0x850A64BC: "cops_damaged",
    0x8ED622AD: "racing_ticket",
    0x9201E1F4: "speeding_ticket",
    0x9E3EBB78: "speedtrap_speed",
    0x9F8E56CE: "cops_in_pursuit",
    0xA61CAC24: "total_infractions",
    0xABDF316E: "reckless_ticket",
    0xC8993341: "opponents_damaged",
    0xCA9AFDF0: "total_cops_in_pursuit",
    0xCDF36FC2: "tire_spikes_dodged",
    0xDCFC0710: "cost_to_state",
    0xE9A4423C: "heat_meter",
    0xEB45F99D: "roadblocks_dodged",
    0xFD989A3A: "cost_to_state_in_pursuit",
}

# Display label + value unit for the 8 types career milestones actually use.
# Units: "count" (integer), "seconds" (duration), "money" (dollars).
CAREER_TYPE_INFO: Dict[str, Tuple[str, str]] = {
    "bounty_in_pursuit": ("Bounty (single pursuit)", "money"),
    "cops_damaged": ("Cops Damaged", "count"),
    "cost_to_state_in_pursuit": ("Cost to State (single pursuit)", "money"),
    "pursuit_evasion_time": ("Evade Within", "seconds"),
    "pursuit_length": ("Pursuit Length", "seconds"),
    "roadblocks_dodged": ("Roadblocks Dodged", "count"),
    "tire_spikes_dodged": ("Tire Spikes Dodged", "count"),
    "total_infractions": ("Infractions", "count"),
}

# ChallengeKey -> VLT node path.
CHALLENGE_NODES: Dict[int, str] = {
    0x01C7D338: "milestones/bin_12/challenge_12_cops_damaged",
    0x0484FF7F: "milestones/bin_05/challenge_5_pursuit_evasion_time",
    0x04D7E7EA: "milestones/bin_02/challenge_2_cost_to_state",
    0x052181A7: "milestones/bin_07/challenge_7_cost_to_state",
    0x0BDA7649: "milestones/bin_15/challenge_15_pursuit_length",
    0x145F05E8: "milestones/bin_02/challenge_2_pursuit_length",
    0x16AE30D4: "milestones/bin_02/challenge_2_tire_spikes_dodged",
    0x1BB746EB: "milestones/bin_13/challenge_13_cops_destroyed",
    0x1CA05C05: "milestones/bin_05/challenge_5_cost_to_state",
    0x207127A2: "milestones/bin_04/challenge_4_cops_damaged",
    0x218B40A6: "milestones/bin_06/challenge_6_cops_damaged",
    0x256EB1B0: "milestones/bin_15/challenge_15_pursuit_evasion_time",
    0x274D85CE: "milestones/bin_03/challenge_3_cops_destroyed",
    0x29176689: "milestones/bin_05/challenge_5_tire_spikes_dodged",
    0x2E923995: "milestones/bin_08/challenge_8_total_infractions",
    0x316CD6F7: "milestones/bin_06/challenge_6_tire_spikes_dodged",
    0x3A045A92: "milestones/bin_08/challenge_8_tire_spikes_dodged",
    0x3C108490: "milestones/bin_11/challenge_11_cost_to_state",
    0x3CCEE94E: "milestones/bin_12/challenge_12_pursuit_evasion_time",
    0x438F4865: "milestones/bin_04/challenge_4_cops_destroyed",
    0x444024C8: "milestones/bin_01/challenge_1_pursuit_evasion_time",
    0x462E0490: "milestones/bin_15/challenge_15_cops_damaged",
    0x4C80268B: "milestones/bin_12/challenge_12_pursuit_length",
    0x5896DF36: "milestones/bin_05/challenge_5_cops_destroyed",
    0x6073D7FF: "milestones/bin_08/challenge_8_pursuit_length",
    0x628647A7: "milestones/bin_01/challenge_1_cops_destroyed",
    0x66300AE5: "milestones/bin_09/challenge_9_pursuit_evasion_time",
    0x6C3BC23C: "milestones/bin_08/challenge_8_cops_damaged",
    0x6F416128: "milestones/bin_04/challenge_4_cost_to_state",
    0x750E24B0: "milestones/bin_14/challenge_14_cost_to_state",
    0x76845207: "milestones/bin_11/challenge_11_roadblocks_dodged",
    0x78C71DD9: "milestones/bin_01/challenge_1_cops_damaged",
    0x82D2A570: "milestones/bin_07/challenge_7_roadblocks_dodged",
    0x8A1AF836: "milestones/bin_07/challenge_7_cops_destroyed",
    0x913754EE: "milestones/bin_06/challenge_6_roadblocks_dodged",
    0x9181CA38: "milestones/bin_02/challenge_2_roadblocks_dodged",
    0x94FEA36E: "milestones/bin_13/challenge_13_pursuit_evasion_time",
    0x9FFA94B7: "milestones/bin_03/challenge_3_cops_damaged",
    0xA2F7E9E4: "milestones/bin_09/challenge_9_roadblocks_dodged",
    0xA416C923: "milestones/bin_03/challenge_3_pursuit_length",
    0xB2E30E84: "milestones/bin_14/challenge_14_cops_destroyed",
    0xB85FFF8A: "milestones/bin_03/challenge_3_pursuit_evasion_time",
    0xBF729147: "milestones/bin_09/challenge_9_cops_damaged",
    0xC187B3FE: "milestones/bin_01/challenge_1_pursuit_length",
    0xC2490817: "milestones/bin_10/challenge_10_cost_to_state",
    0xCBFEE947: "milestones/bin_09/challenge_9_cops_destroyed",
    0xD11A039D: "milestones/bin_07/challenge_7_pursuit_evasion_time",
    0xD4510EDB: "milestones/bin_14/challenge_14_total_infractions",
    0xE114C924: "milestones/bin_10/challenge_10_pursuit_length",
    0xE4B452D3: "milestones/bin_10/challenge_10_roadblocks_dodged",
    0xEEEB129F: "milestones/bin_13/challenge_13_cops_damaged",
    0xF7C4A1BB: "milestones/bin_10/challenge_10_cops_destroyed",
    0xF94E0F6C: "milestones/bin_06/challenge_6_pursuit_length",
    0xFAD6F623: "milestones/bin_11/challenge_11_total_infractions",
    0xFBD181B8: "milestones/bin_04/challenge_4_total_infractions",
}

# Speedtrap key -> VLT node path.
SPEEDTRAP_NODES: Dict[int, str] = {
    0x0896A321: "speedtraps/bin_07/speedtrap2",
    0x0EA540FD: "speedtraps/bin_07/speedtrap1",
    0x1ECE6A5C: "speedtraps/bin_02/speedtrap1",
    0x230027EA: "speedtraps/bin_12/speedtrap1",
    0x399538CB: "speedtraps/bin_04/speedtrap3",
    0x3DE8D0FA: "speedtraps/bin_06/speedtrap2",
    0x3EAFCCF5: "speedtraps/bin_07/speedtrap3",
    0x46D4DB1A: "speedtraps/bin_14/speedtrap1",
    0x4A155DEF: "speedtraps/bin_05/speedtrap1",
    0x4CA5E589: "speedtraps/bin_01/speedtrap1",
    0x56BA924F: "speedtraps/bin_06/speedtrap1",
    0x5B250395: "speedtraps/bin_05/speedtrap3",
    0x5CDE8BF1: "speedtraps/bin_02/speedtrap3",
    0x627CCD2F: "speedtraps/bin_04/speedtrap1",
    0x64AD9C28: "speedtraps/bin_01/speedtrap3",
    0x66BD2A29: "speedtraps/bin_14/speedtrap2",
    0x6B705DB0: "speedtraps/bin_10/speedtrap3",
    0x6EB16947: "speedtraps/bin_02/speedtrap2",
    0x70AF6CFA: "speedtraps/bin_04/speedtrap2",
    0x7282245D: "speedtraps/bin_08/speedtrap3",
    0x75575DA9: "speedtraps/bin_10/speedtrap1",
    0x7CF3F759: "speedtraps/bin_10/speedtrap2",
    0x854EACAC: "speedtraps/bin_09/speedtrap3",
    0xA3D3F573: "speedtraps/bin_15/speedtrap1",
    0xB90DEF2C: "speedtraps/bin_06/speedtrap3",
    0xBC920CD3: "speedtraps/bin_13/speedtrap1",
    0xBF6C2DDB: "speedtraps/bin_11/speedtrap2",
    0xBFEAEEFA: "speedtraps/bin_13/speedtrap2",
    0xCB5B39A2: "speedtraps/bin_08/speedtrap2",
    0xD63DC506: "speedtraps/bin_03/speedtrap3",
    0xDC891E3C: "speedtraps/bin_08/speedtrap1",
    0xDF2A6EC5: "speedtraps/bin_03/speedtrap1",
    0xE383D927: "speedtraps/bin_09/speedtrap2",
    0xE6F92589: "speedtraps/bin_11/speedtrap1",
    0xE7D84CD1: "speedtraps/bin_01/speedtrap2",
    0xF24E233A: "speedtraps/bin_09/speedtrap1",
    0xF548127F: "speedtraps/bin_12/speedtrap2",
    0xFD557FDE: "speedtraps/bin_03/speedtrap2",
    0xFDDBCA52: "speedtraps/bin_05/speedtrap2",
}


def resolve_type_name(type_key: int) -> Optional[str]:
    """Engine stat name for a GMilestone.TypeKey, or None."""
    return MILESTONE_TYPE_NAMES.get(type_key)


def type_label_and_unit(type_key: int) -> Optional[Tuple[str, str]]:
    """(display label, unit) for a career milestone TypeKey, or None."""
    name = MILESTONE_TYPE_NAMES.get(type_key)
    if name is None:
        return None
    return CAREER_TYPE_INFO.get(name)


def resolve_challenge_node(challenge_key: int) -> Optional[str]:
    """VLT node path for a GMilestone.ChallengeKey, or None."""
    return CHALLENGE_NODES.get(challenge_key)


def resolve_speedtrap_node(trap_hash: int) -> Optional[str]:
    """VLT node path for a speedtrap record key, or None."""
    return SPEEDTRAP_NODES.get(trap_hash)


def speedtrap_ordinal(trap_hash: int) -> Optional[int]:
    """1-based in-bin ordinal (speedtrapN suffix), or None."""
    node = SPEEDTRAP_NODES.get(trap_hash)
    if node is None:
        return None
    return int(node.rsplit("speedtrap", 1)[1])
