"""Canonical race display names and race types for career events.

RACE_DISPLAY_NAMES: EventID -> in-game track name (TRACKNAME_* labels in
LANGUAGES/Labels.bin + English.bin; reversed layouts keep their own canon
names). RACE_TYPE_LABELS: EventID type digit -> race mode, ground truth
harvested from the events' internal names in GLOBAL/gameplay.bin
(e.g. "race_bin_05/5_2_3_sprint"); 8/9 are the challenge series.

Generated by RE/tools/gen_race_display_names.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Dict, Optional

RACE_TYPE_LABELS: Dict[int, str] = {
    1: 'Circuit',
    2: 'Sprint',
    3: 'Lap Knockout',
    4: 'Tollbooth',
    5: 'Speedtrap',
    7: 'Drag',
    8: 'Challenge',
    9: 'Challenge',
}

RACE_DISPLAY_NAMES: Dict[str, str] = {
    '1.1.1': 'Hastings',
    '1.1.2': 'Clubhouse',
    '1.2.1': 'Hwy 2001',
    '1.2.2': 'Diamond Park',
    '1.2.3': 'Clubhouse & Lennox',
    '1.2.4': 'Industrial & Bristol',
    '1.3.1': "Smuggler's Wharf",
    '1.4.1': 'Route 55 & Chase',
    '1.4.2': 'Petersburg & Camdem',
    '1.5.1': 'Union Row & Seaside',
    '1.5.2': 'Warrent',
    '1.5.3': 'Ironhorse & Bristol',
    '1.7.1': 'Hollis Boulevard',
    '1.7.1.r': 'State Street',
    '1.7.2': 'Riverfront & Valley',
    '1.7.3': 'Terrace & Riverside',
    '2.1.1': 'Campus Interchange',
    '2.1.1.r': 'Country Club',
    '2.2.1': 'Seaside Interchange',
    '2.2.1.r': 'Bay Bridge & Seaside',
    '2.4.1': 'Beacon & Petersburg',
    '2.4.2': 'Petersburg & Bond',
    '2.4.3': 'Bond & Beacon Bridge',
    '2.4.3.r': 'Marina & Lennox',
    '2.5.1': 'Lennox & Camden',
    '2.7.1': 'Camden & Seaside',
    '2.7.3': 'Row & Rockridge',
    '2.7.3.r': 'Rockridge & Ironwood',
    '3.1.1': 'Omega & Industries',
    '3.1.1.r': 'Oil Refinery',
    '3.1.2': 'Camden Tunnel',
    '3.1.2.r': 'Bay Bridge',
    '3.2.1': 'Seagate & Camden',
    '3.2.1.r': 'Camden & Dunwich',
    '3.2.2': 'Seaside & Lennox',
    '3.3.1': 'Riverside',
    '3.3.1.r': 'Petersburg Crossing',
    '3.3.2': 'Valley Interchange',
    '3.3.2.r': 'Valley & Hwy 201',
    '3.4.1': 'Petersburg Projects',
    '3.4.1.r': 'Petersburg & Project',
    '3.5.1': 'Heritage & Warrent',
    '3.5.2': 'Masterson & Route 55',
    '3.7.1': 'Warrent & Hwy 201',
    '3.7.2': 'Forest & Highlands',
    '3.7.3': 'Boardwalk & Bayshore',
    '4.1.1': 'Waterfront',
    '4.2.1': 'Forest Green',
    '4.2.1.r': 'Hwy 99 & Projects',
    '4.2.2': 'Ocean Hills & Beacon',
    '4.3.1': 'Chancellor Way',
    '4.3.1.r': 'College Switchback',
    '4.4.1': 'North Bay & Beacon',
    '4.4.1.r': 'Wharf & North Bay',
    '4.5.1': 'Hwy 99',
    '4.5.1.r': 'Petersburg & Hwy 201',
    '4.5.2': 'Dunwich & Hills',
    '4.5.3': 'Terminal & Financial',
    '4.7.1': 'Industrial & Hwy 201',
    '4.7.2': 'Hickley & State',
    '4.7.3': 'Asylum & Route 55',
    '4.7.4': 'Rosewood & Heritage',
    '5.1.1': 'Ironhorse',
    '5.1.1.r': 'East Park',
    '5.2.1': 'Lyons & State',
    '5.2.1.r': 'State & Warrent',
    '5.2.2': 'Beach & Chancellor',
    '5.2.3': 'Camden & Fisher',
    '5.3.1': 'Dunwich Village',
    '5.4.1': 'Stadium & Beacon',
    '5.4.1.r': 'Beacon & Riverfront',
    '5.5.1': 'Country Club',
    '5.5.1.r': 'Industrial & Green',
    '5.5.2': 'Fairmont & Clubhouse',
    '5.5.2.r': 'Green & Fairmont',
    '5.5.3': 'Bond & Riverside',
    '5.5.4': 'State & Petersburg',
    '5.7.1': 'Seagate & Omega',
    '5.7.2': 'Coast & Beacon Point',
    '5.7.3': 'North Bay & Fisher',
    '5.7.4': 'Projects & Stadium',
    '6.1.1': 'Little Italy',
    '6.2.1': 'Hwy 201 & Lyons',
    '6.2.2': 'West Park & Lyons',
    '6.2.3': 'Bond & Country Club',
    '6.3.1': 'Coastal',
    '6.3.1.r': 'Industrial Front',
    '6.4.1': 'Interchange & Tunnel',
    '6.4.1.r': 'Bay Bridge & Forest',
    '6.4.2': 'Penitentiary',
    '6.5.1': 'Boardwalk',
    '6.5.2': 'North Bay & College',
    '6.5.3': 'Hwy 99 & Campus',
    '7.1.1': 'Heritage & Omega',
    '7.2.1': 'Interchange & Bond',
    '7.2.1.r': 'Bond & Forest Green',
    '7.2.2': 'Diamond Valley',
    '7.2.2.r': 'Valley & State',
    '7.2.3': 'Stadium & Chase',
    '7.3.1': 'Century',
    '7.4.1': 'Hwy 201 & Hwy 99',
    '7.4.1.r': 'Hwy 201 & Forest',
    '7.4.2': 'Beach & Skyview',
    '7.4.2.r': 'Skyview & Coast',
    '7.4.3': 'Route 55 & Projects',
    '7.4.3.r': 'Industrial & Omega',
    '7.5.1': 'Fisher & Interchange',
    '7.7.1.r': 'Riverside & Terrace',
    '7.7.3': 'Projects & Warrent',
    '7.7.3.r': 'Hwy 201 & Seaside',
    '7.7.4': 'Ocean & Harbor',
    '8.2.1': 'Camden & Ironwood',
    '8.2.1.r': 'Union Row & Ocean',
    '8.2.2': 'Heritage & Diamond',
    '8.3.1': 'Cascade',
    '8.3.2': 'Hwy 201',
    '8.5.1': 'Dunwich & Bayshore',
    '8.5.2': 'Rose & Rockridge',
    '8.7.1': 'Riverfront & Hwy 201',
    '8.7.1.r': 'Riverfront Stadium',
    '8.7.2': 'Petersburg & Hwy 1',
    '8.7.3': 'Stadium & Projects',
    '8.7.3.r': 'Hwy 201',
    '8.7.5': 'Union & Rockridge',
    '9.1.1': 'Dunwich Bay',
    '9.1.1.r': 'Gray Point',
    '9.2.1': 'Camden & Route 55',
    '9.2.2': 'Boardwalk & Boundary',
    '9.2.2.r': 'Ironhorse & Coast',
    '9.3.1': 'Fisher Road',
    '9.4.1': 'Skyview & Waterfront',
    '9.4.1.r': 'Waterfront & Hwy 99',
    '9.4.2': 'Bristol & Route 55',
    '9.5.1': 'Seagate & Horn',
    '9.5.2': 'Hollis & Chancellor',
    '9.5.3': 'North Bay Cannery',
    '9.7.1': 'Seaside & Camden',
    '9.7.1.r': 'Cannery & Bristol',
    '10.2.1': 'North Bay & Harbor',
    '10.2.2': 'Stadium & Hwy 1',
    '10.3.1': 'Ocean Hills',
    '10.3.2': 'Bayshore',
    '10.4.1': 'Waterfront & Bristol',
    '10.4.2': 'Hwy 99 & Union',
    '10.4.2.r': 'Union & Hwy 99',
    '10.7.1': 'Heritage & Boardwalk',
    '10.7.1.r': 'Boardwalk & Heritage',
    '10.7.2': 'Dunwich & Coast',
    '10.7.2.r': 'Coast & Dunwich',
    '10.7.3': 'Harbor & Ocean',
    '11.1.1': 'Hillcrest Boundary',
    '11.1.2': 'Circle Rose',
    '11.1.2.r': 'Hospital Switchback',
    '11.2.1': 'Beacon & Station',
    '11.2.1.r': 'Boundary & Marina',
    '11.4.1': 'Route 55 & North Bay',
    '11.4.2': 'Chase & Waterfront',
    '11.5.1': 'Seaside & Fisher',
    '11.5.1.r': 'North Bay & Seaside',
    '11.5.2': 'Rosewood & Hwy 99',
    '11.7.1': 'Heritage & Rosewood',
    '12.1.1': 'Omega',
    '12.1.1.r': 'Boundary',
    '12.1.2': 'Diamond',
    '12.1.2.r': 'Switchback',
    '12.2.1': 'Chase & Bristol',
    '12.2.1.r': 'Bristol & Bayshore',
    '12.4.1': 'Hwy 99 & Route 55',
    '12.4.2': 'North Bay & Chase',
    '12.5.1': 'Hwy 4 & Clubhouse',
    '12.7.1': 'Route 55 & Camden',
    '12.7.2': 'Chase & Clubhouse',
    '12.7.3': 'Bayshore & Boardwalk',
    '12.7.3.r': 'Rosewood Circle',
    '13.2.1': 'Rosewood & Lyons',
    '13.2.2': 'Campus & Chancellor',
    '13.2.2.r': 'Chancellor & Campus',
    '13.2.3': 'Union & Hollis',
    '13.3.1': 'City Center',
    '13.3.1.r': 'Stadium',
    '13.3.2': 'Rosewood Drive',
    '13.4.1': 'Hwy 99 & Highlands',
    '13.4.2': 'Hwy 4 & Forest Green',
    '13.5.1': 'Diamond & State',
    '13.5.2': 'Forest & Ironwood',
    '14.1.1': 'Petersburg',
    '14.1.2': 'Heritage Heights',
    '14.2.1': 'Hwy 99 & State',
    '14.2.2': 'Clubhouse & Hollis',
    '14.2.2.r': 'Heritage & Campus',
    '14.2.3': 'Rockridge & Union',
    '14.2.4': 'Stadium & Hwy 99',
    '14.3.1': 'Rosewood College',
    '14.3.1.r': 'Rosewood Hillcrest',
    '14.4.1': 'Skyview & Campus',
    '15.1.1': 'Ironwood Estates',
    '15.1.1.r': 'Highlands',
    '15.1.2': 'Campus Way',
    '15.2.1': 'Diamond & Union',
    '15.2.1.r': 'Rosewood & State',
    '15.3.1': 'Hickley Field',
    '16.1.1': 'Warrent Road',
    '16.1.1.r': 'Century Square',
    '16.2.1': 'Riverfront & Marina',
    '16.2.2': 'Financial & Shipyard',
    '16.2.3': 'Waterfront & Century',
    '21.1.1': 'City Perimeter',
    '21.2.1': 'Seaside & Power Station',
    '21.2.2': 'NFS World Loop',
    '50.1.1': 'E3 Demo Race',
}

# Curated (no TRACKNAME exists): gameplay.bin names event 1.8.1
# "race_bin_01/epic_pursuit" - the post-showdown Final Pursuit. The separate
# Warrent speedtrap (1.5.2) is the stage-1 challenge event with no save-table
# slot; its presence and order come from the gameplay challenge catalog.
CURATED_NAMES: Dict[str, str] = {
    '1.8.1': 'Final Pursuit',
}
CURATED_TYPES: Dict[str, str] = {
    '1.8.1': 'Pursuit',
}


def display_name(event_id: Optional[str]) -> Optional[str]:
    """Canon track name for an EventID; reversed falls back to the base
    route when the game defines no dedicated _R name."""
    if not event_id:
        return None
    name = RACE_DISPLAY_NAMES.get(event_id) or CURATED_NAMES.get(event_id)
    if name is None and event_id.endswith(".r"):
        name = RACE_DISPLAY_NAMES.get(event_id[:-2])
    return name


def type_label(event_id: Optional[str]) -> Optional[str]:
    if not event_id:
        return None
    curated = CURATED_TYPES.get(event_id)
    if curated is not None:
        return curated
    parts = event_id.split(".")
    if len(parts) < 3:
        return None
    try:
        return RACE_TYPE_LABELS.get(int(parts[1]))
    except ValueError:
        return None
