"""Canonical Blacklist rival bios from the game's language data.

Key = Blacklist rank (1 = Razor ... 15 = Sonny), matching
ui/pages/constants.BLACKLIST_BOSS_NAMES. Source: LANGUAGES/Labels.bin +
English.bin labels blacklist_rival_NN_bio - the Rival Challenge screen's
Bio toggle text. Game font markup normalized (soft breaks, curly quotes,
apostrophes); bio 6 keeps the engine's “take ’m on” verbatim.

Generated by RE/tools/gen_rival_bios.py. Do not edit by hand.
"""
from __future__ import annotations

import re
from typing import Dict, Optional

RIVAL_BIOS: Dict[int, str] = {
    1: "Razor rocketed to the top of the Blacklist using your ride. Now he's holding it down and rolling the streets like he owns them. He'll do anything he can to give himself an edge. That includes messin' with your head. Remember, you can't trust anything he says.",
    2: "If it weren't for Razor, Toru would still be hanging down at the docks dreamin' of the Blacklist. This fool thinks he's got a sleeper, calls it reverse psychology. The only thing stock on his ride is the paint. Toru likes to keep his car mint so give him a bump when you can.",
    3: "You know Ronnie. He's one of those rich freaks that thinks he's ghetto. He definitely ain't from around the way. Got his car as a graduation gift from his parents. Don't be fooled though, the guy knows how to drive. He's been to every race school you can think of.",
    4: "I don't know how JV does it, man. His nights are spent in the clubs and days on the streets. This guy's got a lot of street rep. Cops hate him and racers want to be like him. His flash green Dodge Viper has cops swarming around it all the time.",
    5: "Webster's always talking about rides, performance, racers, blah, blah, blah. Won't shut up. He's got some crazy idea that he's gonna make it big. When he ain't street racing, he's hanging out at shops. His ride is tuned to the max. Apparently the interior is stripped of everything that isn't related to speed.",
    6: "This here is Ming. He prides himself on keeping his ride looking stock. He's fast and shreds radar traps everywhere he can. He's the straight goods. Word is he got his ride from some rich cat who talked when he should have been listening. Don't take ’m on until you're ready.",
    7: "Kaze is crazy. What she can't conquer with skills, she demolishes with speed. Don't let her sweet looks fool ya. She'll trash anything she sees, including you. She's not afraid to ding her ride to put you out of commission.",
    8: "This sweet thing goes by the name Jewels. She's all about big block and muscle. She's got a lot of mileage under her wheels so don't be tempted to do anything stupid. She's got some serious power under the hood.",
    9: "This guy hails from the lower eastside of Rockport but now rides on the coast. He's a big fan of imports and goes out of his way to take on the big blocks.",
    10: "This flake calls himself “Baron”. He's a rich guy from the coast. He thinks garage custom is an excuse for being broke. As far as he's concerned, “if it's not name brand, it's nothing.” Go show ’m what home grown rides can do.",
    11: "This slab of Korean muscle considers himself a real ladies man. He's all show. Rumor has it; he panics around the cops and bails on races the first chance he gets. Along with that they say he has problems working the clutch so he's slow off the line. I wouldn't count on it if I was you.",
    12: "Izzy is definitely a chick you don't want to mess with. She knows everything there is about cars, on and off the road. She's got her ride wired tight. She comes from a long line of race fanatics. Everybody she runs with is either a cousin, friend or uncle. They all stick close so don't get on her bad side.",
    13: "This dude's been holding it down in the #13 slot for a while now. He can't break out of his rut and no one can run him out. He's slack and dangerous but knows how to handle his ride. He'll smoke you if he gets the chance.",
    14: 'This crazy fool is a major heat score. Blacklist gave him the name “Taz”. He hates cops and they hate him. Watch yourself around this guy. He prowls the streets of Rosewood looking for newbies.',
    15: "This here is Sonny. He's dumped a whole lot of cash into his car. That ride is worked so don't be fooled, it's a rocket. He does anything he can to get a hold of parts before they hit the streets.",
}

_SENTENCE_END = re.compile(r"(?<=[.!?])\s+")


def bio(stage: int) -> Optional[str]:
    """Full canon bio for a Blacklist rank, or None."""
    return RIVAL_BIOS.get(stage)


def tagline(stage: int) -> Optional[str]:
    """First sentence of the rank's bio - the hero one-liner."""
    text = RIVAL_BIOS.get(stage)
    if text is None:
        return None
    return _SENTENCE_END.split(text, 1)[0]
