"""Canon per-rival race order from gameplay.bin race-bin child vaults.

BOSS_SERIES: stage -> Rival Challenge events in the game's screen order
(stage 1 ends with 1.8.1, the Final Pursuit; 1.5.2 opens it and has no
save-table slot). WORLD_ORDER: stage -> the chapter's regular events in
the same vault order. Source: BossRaces / world-race GCollectionKey
arrays ({u16 count, u16 alloc, u32 stride} + lookup2 hashes of
"race_bin_NN/<event>" paths), cross-validated against the offering
ladder (core/race_chapters.py) and an in-game Rival Challenge
screenshot of the Razor series.

Generated by RE/tools/gen_rival_challenge.py. Do not edit by hand.
"""
from __future__ import annotations

from typing import Dict, Tuple

BOSS_SERIES: Dict[int, Tuple[str, ...]] = {
    1: ('1.5.2', '1.7.3', '4.2.1', '1.1.2', '1.2.3', '1.8.1'),
    2: ('3.1.1.r', '9.2.2.r', '2.2.1'),
    3: ('3.1.2.r', '3.2.2', '3.1.2'),
    4: ('4.5.2', '4.7.4', '4.5.1.r'),
    5: ('5.2.2', '5.5.4', '5.2.1.r'),
    6: ('6.1.1', '6.5.2'),
    7: ('7.2.2', '7.2.3'),
    8: ('8.2.1', '8.7.5'),
    9: ('9.5.3', '9.2.1'),
    10: ('10.2.1', '10.7.3'),
    11: ('11.1.2', '12.1.2.r'),
    12: ('12.2.1', '12.1.2'),
    13: ('13.2.3', '14.2.2.r'),
    14: ('14.2.4', '15.2.1'),
    15: ('15.1.2', '15.1.1'),
}

WORLD_ORDER: Dict[int, Tuple[str, ...]] = {
    1: ('1.1.1', '1.2.1', '1.2.2', '1.2.4', '1.3.1', '1.4.1', '1.4.2', '1.5.1', '1.5.3', '2.2.1.r', '2.4.3.r'),
    2: ('2.1.1', '2.1.1.r', '2.4.1', '2.4.2', '2.4.3', '2.5.1', '3.2.1.r', '3.3.1.r', '3.3.2.r', '5.1.1.r', '5.5.1.r', '2.7.1'),
    3: ('3.2.1', '3.3.1', '3.1.1', '3.4.1', '7.2.1.r', '4.3.1.r', '3.5.1', '3.5.2', '3.4.1.r', '4.4.1.r', '4.2.1.r', '3.7.3'),
    4: ('4.4.1', '4.1.1', '4.3.1', '4.5.3', '4.5.1', '5.5.2.r', '7.2.2.r', '6.3.1.r', '9.1.1.r', '5.4.1.r', '7.4.3.r'),
    5: ('5.3.1', '5.1.1', '5.2.1', '5.5.1', '5.5.2', '5.4.1', '5.5.3', '5.2.3', '6.4.1.r', '7.4.2.r'),
    6: ('6.2.2', '6.4.1', '6.5.1', '6.2.1', '6.4.2', '6.3.1', '14.3.1.r', '6.2.3', '6.5.3', '7.7.1.r', '7.4.1.r'),
    7: ('7.2.1', '7.4.3', '7.5.1', '7.4.1', '7.3.1', '16.1.1.r', '8.2.1.r', '7.1.1', '7.4.2', '7.7.4'),
    8: ('8.3.1', '8.3.2', '8.5.1', '8.5.2', '8.2.2', '10.4.2.r', '9.4.1.r'),
    9: ('9.1.1', '9.7.1', '9.4.1', '9.5.1', '9.5.2', '9.4.2', '12.1.1.r', '9.3.1'),
    10: ('10.3.1', '10.3.2', '10.4.2', '10.4.1', '11.2.1.r', '10.2.2', '11.1.2.r', '11.5.1.r'),
    11: ('11.2.1', '11.1.1', '11.5.1', '11.4.2', '11.4.1', '12.2.1.r', '11.5.2', '11.7.1'),
    12: ('12.1.1', '12.4.1', '12.4.2', '12.5.1', '12.7.3', '13.2.2.r', '14.2.3.r'),
    13: ('13.2.1', '13.3.1', '13.3.2', '13.4.1', '13.4.2', '13.5.1', '13.5.2'),
    14: ('14.1.1', '14.2.1', '14.2.2', '14.3.1', '14.4.1', '14.1.2'),
    15: ('15.1.1', '15.2.1', '15.3.1'),
}

# Save slots whose driven route is a different EventID: the vault's world
# list references the route the player actually drives; the save tracks
# its own slot id. Display names should follow the ROUTE.
ROUTE_REMAP: Dict[str, str] = {
    '8.3.2': '13.3.1.r',
}
